
name: CI

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"
      - run: |
          rustup target add wasm32-unknown-unknown

      - uses: taiki-e/install-action@cargo-llvm-cov
        continue-on-error: true
          
      - run: cargo llvm-cov --lcov --output-path lcov.info
  
      - uses: codecov/codecov-action@v5
        continue-on-error: true
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: ./lcov.info
